CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name VARCHAR (255) UNIQUE NOT NULL,
    password VARCHAR (225) NOT NULL,
    farm_name TEXT NOT NULL,
    street_address TEXT NOT NULL,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    zip TEXT NOT NULL
);


CREATE TABLE items (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    users_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL, 
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    itemCount TEXT NOT NULL,
    itemPrice TEXT NOT NULL,
    img TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now () NOT NULL
);



INSERT INTO public.users
    (user_name,"password")
VALUES
    ('demo@gmail.com', '$2a$12$9j6A6wxbKIP8IQWwHExsue5kimTsdwzOSTJa/kusQN69u1lm0J856')
,
    ('user@gmail.com', '$2a$12$KI8Mth8npH21ez6SCBy.pOli8jVI0IF5Z9dWj/JQWUA2ATi8IoQam')
;